# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-112060364-1'

menu:
- {name: 'درباره ما', path: 'menu', url: 'about.html'}
- {name: 'آرشیو مطالب', path: 'menu', url: 'writing.html'}
- {name: 'تماس با ما', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/'}
- {icon: 'twitter', link: 'https://twitter.com/'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/'}
- {icon: 'envelope', link: 'mailto:matlabprojectsonline@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'جدیدتر'
  previous_page: 'قدیمی‌تر'

sharing_button_prompt: 'اشتراک‌گذاری'

related_posts: 'این‌ها را نیز دوست دارید :'

post_date_prefix: 'نوشته‌شده در '
